const quizQuestions = {
  sun: [
    {
      id: 1,
      question: "What is the Sun's core temperature?",
      options: ["5,500°C", "1 million °C", "15 million °C", "100 million °C"],
      correct: 2,
    },
    {
      id: 2,
      question: "What is the Sun mainly composed of?",
      options: [
        "Iron and Nickel",
        "Hydrogen and Helium",
        "Carbon and Oxygen",
        "Nitrogen and Methane",
      ],
      correct: 1,
    },
    {
      id: 3,
      question: "How old is the Sun?",
      options: ["2.1 billion years", "4.6 billion years", "6.8 billion years", "10 billion years"],
      correct: 1,
    },
    {
      id: 4,
      question: "What type of star is the Sun classified as?",
      options: ["Red Dwarf", "Blue Giant", "G2V Yellow Dwarf", "White Dwarf"],
      correct: 2,
    },
    {
      id: 5,
      question: "How long does sunlight take to reach Earth?",
      options: ["1 minute", "8 minutes 20 seconds", "24 minutes", "1 hour"],
      correct: 1,
    },
    {
      id: 6,
      question: "What is the Sun's surface temperature?",
      options: ["1,000°C", "5,500°C", "15,000°C", "50,000°C"],
      correct: 1,
    },
    {
      id: 7,
      question: "How does the Sun's mass compare to Earth?",
      options: ["1,000 x Earth", "33,000 x Earth", "333,000 x Earth", "1 million x Earth"],
      correct: 2,
    },
    {
      id: 8,
      question: "What powers the Sun?",
      options: [
        "Chemical combustion",
        "Nuclear fission",
        "Nuclear fusion",
        "Gravitational collapse",
      ],
      correct: 2,
    },
    {
      id: 9,
      question: "How long is the Sun's rotation period?",
      options: ["1 day", "7 days", "25-35 days", "365 days"],
      correct: 2,
    },
    {
      id: 10,
      question: "What percentage of the solar system's mass does the Sun contain?",
      options: ["50%", "75%", "90%", "99.8%"],
      correct: 3,
    },
  ],
  mercury: [
    {
      id: 1,
      question: "How long does one day on Mercury last?",
      options: ["24 hours", "59 Earth days", "88 Earth days", "12 hours"],
      correct: 1,
    },
    {
      id: 2,
      question: "How many moons does Mercury have?",
      options: ["1", "2", "0", "3"],
      correct: 2,
    },
    {
      id: 3,
      question: "What is Mercury's orbital speed?",
      options: ["29.78 km/s", "35.02 km/s", "47.36 km/s", "58.98 km/s"],
      correct: 2,
    },
    {
      id: 4,
      question: "Is Mercury the hottest planet in the solar system?",
      options: [
        "Yes, it is closest to the Sun",
        "No, Venus is hotter",
        "No, Jupiter's core is hotter",
        "It ties with Venus",
      ],
      correct: 1,
    },
    {
      id: 5,
      question: "How long is a year on Mercury?",
      options: ["59 Earth days", "88 Earth days", "165 Earth days", "225 Earth days"],
      correct: 1,
    },
    {
      id: 6,
      question: "What is Mercury's surface gravity compared to Earth?",
      options: ["10%", "25%", "38%", "50%"],
      correct: 2,
    },
    {
      id: 7,
      question: "What is special about Mercury's core?",
      options: [
        "It is hollow",
        "It is made of diamond",
        "Iron core takes up ~75% of its radius",
        "It has no core",
      ],
      correct: 2,
    },
    {
      id: 8,
      question: "What type of atmosphere does Mercury have?",
      options: [
        "Thick carbon dioxide",
        "Nitrogen and oxygen",
        "Almost none (exosphere)",
        "Hydrogen and helium",
      ],
      correct: 2,
    },
    {
      id: 9,
      question: "What is Mercury's temperature range?",
      options: [
        "0°C to 100°C",
        "-50°C to 200°C",
        "-180°C to 430°C",
        "-270°C to 500°C",
      ],
      correct: 2,
    },
    {
      id: 10,
      question: "What is Mercury's diameter?",
      options: ["2,377 km", "3,474 km", "4,879 km", "6,779 km"],
      correct: 2,
    },
  ],
  venus: [
    {
      id: 1,
      question: "What is the surface temperature of Venus?",
      options: ["250°C", "465°C", "180°C", "320°C"],
      correct: 1,
    },
    {
      id: 2,
      question: "How long is a day on Venus compared to its year?",
      options: [
        "Shorter than its year",
        "The same length",
        "Longer than its year",
        "Exactly half its year",
      ],
      correct: 2,
    },
    {
      id: 3,
      question: "What makes Venus's rotation unique?",
      options: [
        "It does not rotate",
        "It spins backwards (retrograde)",
        "It rotates on its side",
        "It has no axial tilt",
      ],
      correct: 1,
    },
    {
      id: 4,
      question: "What is Venus's atmosphere mainly composed of?",
      options: ["Nitrogen", "Oxygen", "Carbon Dioxide", "Methane"],
      correct: 2,
    },
    {
      id: 5,
      question: "How does Venus's surface pressure compare to Earth?",
      options: ["2x Earth", "10x Earth", "45x Earth", "90x Earth"],
      correct: 3,
    },
    {
      id: 6,
      question: "Approximately how many volcanoes does Venus have?",
      options: ["50", "500", "Over 1,600", "Over 10,000"],
      correct: 2,
    },
    {
      id: 7,
      question: "How many moons does Venus have?",
      options: ["0", "1", "2", "3"],
      correct: 0,
    },
    {
      id: 8,
      question: "Venus is often called Earth's what?",
      options: ["Sister", "Twin", "Opposite", "Mirror"],
      correct: 1,
    },
    {
      id: 9,
      question: "What causes Venus's extreme heat?",
      options: [
        "Proximity to the Sun",
        "Volcanic activity",
        "Runaway greenhouse effect",
        "Solar flares",
      ],
      correct: 2,
    },
    {
      id: 10,
      question: "How long is a day on Venus in Earth days?",
      options: ["59 days", "116 days", "243 days", "365 days"],
      correct: 2,
    },
  ],
  earth: [
    {
      id: 1,
      question: "What percentage of Earth's surface is covered in water?",
      options: ["50%", "65%", "71%", "80%"],
      correct: 2,
    },
    {
      id: 2,
      question: "How old is Earth?",
      options: [
        "3.2 billion years",
        "4.54 billion years",
        "5.1 billion years",
        "2.8 billion years",
      ],
      correct: 1,
    },
    {
      id: 3,
      question: "What is Earth's axial tilt?",
      options: ["0°", "12.5°", "23.5°", "45°"],
      correct: 2,
    },
    {
      id: 4,
      question: "What is Earth's atmosphere mainly composed of?",
      options: [
        "Oxygen and Carbon Dioxide",
        "Nitrogen and Oxygen",
        "Hydrogen and Helium",
        "Nitrogen and Carbon Dioxide",
      ],
      correct: 1,
    },
    {
      id: 5,
      question: "How many natural satellites does Earth have?",
      options: ["0", "1", "2", "3"],
      correct: 1,
    },
    {
      id: 6,
      question: "How fast does Earth travel around the Sun?",
      options: ["50,000 km/h", "80,000 km/h", "107,000 km/h", "150,000 km/h"],
      correct: 2,
    },
    {
      id: 7,
      question: "What is Earth's nickname?",
      options: ["The Red Planet", "The Blue Planet", "The Green Planet", "The Water World"],
      correct: 1,
    },
    {
      id: 8,
      question: "What is the coldest temperature ever recorded on Earth?",
      options: ["-55°C", "-71°C", "-89°C", "-100°C"],
      correct: 2,
    },
    {
      id: 9,
      question: "What causes Earth's seasons?",
      options: [
        "Distance from the Sun",
        "The Moon's gravity",
        "Earth's axial tilt",
        "Solar flare cycles",
      ],
      correct: 2,
    },
    {
      id: 10,
      question: "What is Earth's diameter?",
      options: ["6,779 km", "12,104 km", "12,742 km", "49,244 km"],
      correct: 2,
    },
  ],
  mars: [
    {
      id: 1,
      question: "What is the tallest mountain on Mars called?",
      options: ["Mount Everest", "Olympus Mons", "Valles Marineris", "Elysium Mons"],
      correct: 1,
    },
    {
      id: 2,
      question: "How many moons does Mars have?",
      options: ["0", "1", "2", "4"],
      correct: 2,
    },
    {
      id: 3,
      question: "What gives Mars its red color?",
      options: [
        "Copper deposits",
        "Red sand from volcanoes",
        "Iron oxide on the surface",
        "Atmospheric reflection",
      ],
      correct: 2,
    },
    {
      id: 4,
      question: "What are the names of Mars's moons?",
      options: [
        "Io and Europa",
        "Phobos and Deimos",
        "Titan and Rhea",
        "Ganymede and Callisto",
      ],
      correct: 1,
    },
    {
      id: 5,
      question: "How long is a day on Mars?",
      options: ["12 hours", "24 hours 37 minutes", "36 hours", "48 hours"],
      correct: 1,
    },
    {
      id: 6,
      question: "What is the longest valley on Mars?",
      options: [
        "Olympus Canyon",
        "Hellas Basin",
        "Valles Marineris",
        "Utopia Planitia",
      ],
      correct: 2,
    },
    {
      id: 7,
      question: "What is Mars's atmosphere mainly composed of?",
      options: ["Nitrogen", "Oxygen", "Carbon Dioxide", "Methane"],
      correct: 2,
    },
    {
      id: 8,
      question: "How does Mars's gravity compare to Earth?",
      options: ["10% of Earth", "38% of Earth", "62% of Earth", "85% of Earth"],
      correct: 1,
    },
    {
      id: 9,
      question: "How tall is Olympus Mons?",
      options: ["8.8 km", "12.5 km", "21.9 km", "35 km"],
      correct: 2,
    },
    {
      id: 10,
      question: "How long is a year on Mars?",
      options: ["365 Earth days", "500 Earth days", "687 Earth days", "780 Earth days"],
      correct: 2,
    },
  ],
  jupiter: [
    {
      id: 1,
      question: "How many known moons does Jupiter have?",
      options: ["63", "79", "95", "112"],
      correct: 2,
    },
    {
      id: 2,
      question: "What is Jupiter's Great Red Spot?",
      options: [
        "A volcanic crater",
        "A storm larger than Earth",
        "An ocean of liquid hydrogen",
        "A mountain range",
      ],
      correct: 1,
    },
    {
      id: 3,
      question: "How strong is Jupiter's magnetic field compared to Earth?",
      options: ["100x", "1,000x", "20,000x", "1 million x"],
      correct: 2,
    },
    {
      id: 4,
      question: "What is Jupiter's largest moon?",
      options: ["Europa", "Io", "Ganymede", "Callisto"],
      correct: 2,
    },
    {
      id: 5,
      question: "How long is a day on Jupiter?",
      options: ["5 hours", "9 hours 55 minutes", "15 hours", "24 hours"],
      correct: 1,
    },
    {
      id: 6,
      question: "What is Jupiter mainly composed of?",
      options: [
        "Rock and metal",
        "Ice and water",
        "Hydrogen and Helium",
        "Carbon Dioxide and Nitrogen",
      ],
      correct: 2,
    },
    {
      id: 7,
      question: "Does Jupiter have rings?",
      options: [
        "No, only Saturn has rings",
        "Yes, 4 faint rings",
        "Yes, 7 main rings",
        "Yes, 13 rings",
      ],
      correct: 1,
    },
    {
      id: 8,
      question: "How does Jupiter's mass compare to other planets?",
      options: [
        "Same as Saturn",
        "Twice as massive as all other planets combined",
        "Half the mass of Saturn",
        "10x the mass of Earth",
      ],
      correct: 1,
    },
    {
      id: 9,
      question: "What is special about Ganymede?",
      options: [
        "It has active volcanoes",
        "It has liquid water oceans",
        "It is bigger than Mercury",
        "It has a thick atmosphere",
      ],
      correct: 2,
    },
    {
      id: 10,
      question: "How long is a year on Jupiter?",
      options: [
        "5.2 Earth years",
        "11.86 Earth years",
        "29 Earth years",
        "84 Earth years",
      ],
      correct: 1,
    },
  ],
  saturn: [
    {
      id: 1,
      question: "How many main rings does Saturn have?",
      options: ["3", "5", "7", "9"],
      correct: 2,
    },
    {
      id: 2,
      question: "What is unique about Saturn's density?",
      options: [
        "It is the densest planet",
        "It is less dense than water",
        "It has the same density as Earth",
        "Its density changes with seasons",
      ],
      correct: 1,
    },
    {
      id: 3,
      question: "What is Saturn's largest moon?",
      options: ["Enceladus", "Mimas", "Titan", "Rhea"],
      correct: 2,
    },
    {
      id: 4,
      question: "What are Saturn's rings mostly made of?",
      options: [
        "Gas and dust",
        "Ice and rock",
        "Liquid metal",
        "Frozen nitrogen",
      ],
      correct: 1,
    },
    {
      id: 5,
      question: "How many known moons does Saturn have?",
      options: ["82", "95", "120", "146"],
      correct: 3,
    },
    {
      id: 6,
      question: "What unusual feature exists at Saturn's north pole?",
      options: [
        "A giant volcano",
        "A hexagonal storm",
        "A massive crater",
        "An ice cap",
      ],
      correct: 1,
    },
    {
      id: 7,
      question: "What is special about Titan?",
      options: [
        "It is the smallest moon",
        "It has a thick atmosphere",
        "It has no gravity",
        "It orbits backwards",
      ],
      correct: 1,
    },
    {
      id: 8,
      question: "How long is a day on Saturn?",
      options: ["6 hours", "10 hours 42 minutes", "16 hours", "24 hours"],
      correct: 1,
    },
    {
      id: 9,
      question: "How long is a year on Saturn?",
      options: [
        "11.86 Earth years",
        "29.46 Earth years",
        "84 Earth years",
        "164 Earth years",
      ],
      correct: 1,
    },
    {
      id: 10,
      question: "Could Saturn float in water?",
      options: [
        "No, it is too heavy",
        "Yes, its density is less than water",
        "Only if the water was frozen",
        "Only its rings could float",
      ],
      correct: 1,
    },
  ],
  uranus: [
    {
      id: 1,
      question: "What is Uranus's axial tilt?",
      options: ["23.5°", "45°", "97.77°", "120°"],
      correct: 2,
    },
    {
      id: 2,
      question: "What gives Uranus its blue-green color?",
      options: [
        "Liquid water on the surface",
        "Methane in its atmosphere",
        "Copper compounds in the clouds",
        "Reflected light from its rings",
      ],
      correct: 1,
    },
    {
      id: 3,
      question: "What makes Uranus the coldest planet?",
      options: [
        "It is the farthest from the Sun",
        "It has no internal heat source",
        "Its atmosphere blocks all sunlight",
        "Its core is frozen solid",
      ],
      correct: 1,
    },
    {
      id: 4,
      question: "Who discovered Uranus?",
      options: [
        "Galileo Galilei",
        "William Herschel",
        "Johannes Kepler",
        "Isaac Newton",
      ],
      correct: 1,
    },
    {
      id: 5,
      question: "How many known rings does Uranus have?",
      options: ["4", "7", "13", "20"],
      correct: 2,
    },
    {
      id: 6,
      question: "How many known moons does Uranus have?",
      options: ["5", "16", "28", "45"],
      correct: 2,
    },
    {
      id: 7,
      question: "How long is a year on Uranus?",
      options: ["29 Earth years", "84 Earth years", "164 Earth years", "248 Earth years"],
      correct: 1,
    },
    {
      id: 8,
      question: "When was Uranus discovered?",
      options: ["1610", "1781", "1846", "1930"],
      correct: 1,
    },
    {
      id: 9,
      question: "What is Uranus's minimum temperature?",
      options: ["-150°C", "-190°C", "-224°C", "-270°C"],
      correct: 2,
    },
    {
      id: 10,
      question: "How does Uranus orbit compared to other planets?",
      options: [
        "It orbits backwards",
        "It orbits tilted on its side",
        "It has a perfectly circular orbit",
        "It orbits faster than Earth",
      ],
      correct: 1,
    },
  ],
  neptune: [
    {
      id: 1,
      question: "How fast can winds reach on Neptune?",
      options: ["500 km/h", "1,000 km/h", "2,100 km/h", "3,500 km/h"],
      correct: 2,
    },
    {
      id: 2,
      question: "How was Neptune discovered?",
      options: [
        "By telescope observation",
        "By mathematical prediction",
        "By spacecraft flyby",
        "By ancient astronomers",
      ],
      correct: 1,
    },
    {
      id: 3,
      question: "What is Neptune's largest moon?",
      options: ["Nereid", "Proteus", "Triton", "Naiad"],
      correct: 2,
    },
    {
      id: 4,
      question: "What is unusual about Triton's orbit?",
      options: [
        "It is perfectly circular",
        "It orbits backwards (retrograde)",
        "It orbits vertically",
        "It orbits faster than Neptune rotates",
      ],
      correct: 1,
    },
    {
      id: 5,
      question: "How long is a year on Neptune?",
      options: [
        "84 Earth years",
        "124 Earth years",
        "164.8 Earth years",
        "248 Earth years",
      ],
      correct: 2,
    },
    {
      id: 6,
      question: "In what year was Neptune discovered?",
      options: ["1781", "1846", "1930", "1610"],
      correct: 1,
    },
    {
      id: 7,
      question: "What gives Neptune its deep blue color?",
      options: [
        "Liquid water oceans",
        "Methane in its atmosphere",
        "Nitrogen ice",
        "Reflected starlight",
      ],
      correct: 1,
    },
    {
      id: 8,
      question: "What is Neptune's Great Dark Spot?",
      options: [
        "A crater",
        "A storm system similar to Jupiter's",
        "A shadow from its rings",
        "An ocean on the surface",
      ],
      correct: 1,
    },
    {
      id: 9,
      question: "How many known moons does Neptune have?",
      options: ["5", "10", "16", "28"],
      correct: 2,
    },
    {
      id: 10,
      question: "What is Neptune's temperature?",
      options: ["-150°C", "-180°C", "-214°C", "-270°C"],
      correct: 2,
    },
  ],
  pluto: [
    {
      id: 1,
      question: "When was Pluto reclassified as a dwarf planet?",
      options: ["1998", "2002", "2006", "2010"],
      correct: 2,
    },
    {
      id: 2,
      question: "What is the name of Pluto's largest moon?",
      options: ["Europa", "Titan", "Charon", "Ganymede"],
      correct: 2,
    },
    {
      id: 3,
      question: "Who discovered Pluto?",
      options: [
        "William Herschel",
        "Clyde Tombaugh",
        "Galileo Galilei",
        "Edwin Hubble",
      ],
      correct: 1,
    },
    {
      id: 4,
      question: "What is the heart-shaped feature on Pluto called?",
      options: ["Pluto's Heart", "Tombaugh Regio", "Sputnik Plain", "Charon Basin"],
      correct: 1,
    },
    {
      id: 5,
      question: "How many known moons does Pluto have?",
      options: ["1", "3", "5", "7"],
      correct: 2,
    },
    {
      id: 6,
      question: "What spacecraft flew by Pluto in 2015?",
      options: ["Voyager 2", "Cassini", "New Horizons", "Juno"],
      correct: 2,
    },
    {
      id: 7,
      question: "How long is a year on Pluto?",
      options: ["84 Earth years", "164 Earth years", "248 Earth years", "500 Earth years"],
      correct: 2,
    },
    {
      id: 8,
      question: "When was Pluto discovered?",
      options: ["1846", "1900", "1930", "1960"],
      correct: 2,
    },
    {
      id: 9,
      question: "How long is a day on Pluto?",
      options: ["24 hours", "6.4 Earth days", "27 Earth days", "243 Earth days"],
      correct: 1,
    },
    {
      id: 10,
      question: "What is Pluto's heart-shaped region made of?",
      options: ["Water ice", "Carbon dioxide", "Nitrogen ice", "Methane crystals"],
      correct: 2,
    },
  ],
  moon: [
    {
      id: 1,
      question: "When did humans first walk on the Moon?",
      options: ["July 4, 1965", "July 20, 1969", "August 15, 1971", "June 12, 1967"],
      correct: 1,
    },
    {
      id: 2,
      question: "How does the Moon's gravity compare to Earth's?",
      options: ["1/2 of Earth", "1/4 of Earth", "1/6 of Earth", "1/10 of Earth"],
      correct: 2,
    },
    {
      id: 3,
      question: "Why do we always see the same side of the Moon?",
      options: [
        "The Moon does not rotate",
        "It is tidally locked to Earth",
        "The other side is too dark to see",
        "Earth's shadow hides it",
      ],
      correct: 1,
    },
    {
      id: 4,
      question: "How was the Moon likely formed?",
      options: [
        "Captured asteroid",
        "Broke off from Earth's spin",
        "Giant impact (Theia theory)",
        "Formed alongside Earth",
      ],
      correct: 2,
    },
    {
      id: 5,
      question: "How far is the Moon from Earth?",
      options: ["100,000 km", "250,000 km", "384,400 km", "500,000 km"],
      correct: 2,
    },
    {
      id: 6,
      question: "How many astronauts have walked on the Moon?",
      options: ["2", "6", "12", "24"],
      correct: 2,
    },
    {
      id: 7,
      question: "What is the Moon's orbital period?",
      options: ["7 days", "14 days", "27.3 days", "30 days"],
      correct: 2,
    },
    {
      id: 8,
      question: "What is the Moon's diameter?",
      options: ["1,737 km", "2,377 km", "3,474 km", "4,879 km"],
      correct: 2,
    },
    {
      id: 9,
      question: "What are the dark flat areas on the Moon called?",
      options: ["Craters", "Maria (seas)", "Highlands", "Basins"],
      correct: 1,
    },
    {
      id: 10,
      question: "What is the Moon's temperature range?",
      options: [
        "-50°C to 50°C",
        "-100°C to 100°C",
        "-173°C to 127°C",
        "-270°C to 200°C",
      ],
      correct: 2,
    },
  ],
  "asteroid-belt": [
    {
      id: 1,
      question: "Where is the asteroid belt located?",
      options: [
        "Between Earth and Mars",
        "Between Mars and Jupiter",
        "Between Jupiter and Saturn",
        "Beyond Neptune",
      ],
      correct: 1,
    },
    {
      id: 2,
      question: "What is the largest object in the asteroid belt?",
      options: ["Vesta", "Pallas", "Ceres", "Hygiea"],
      correct: 2,
    },
    {
      id: 3,
      question: "What is the total mass of the asteroid belt compared to the Moon?",
      options: ["~4%", "~25%", "~50%", "~100%"],
      correct: 0,
    },
    {
      id: 4,
      question: "What is Ceres classified as?",
      options: ["Asteroid", "Comet", "Dwarf planet", "Minor planet"],
      correct: 2,
    },
    {
      id: 5,
      question: "How far apart are asteroids in the belt on average?",
      options: [
        "A few meters",
        "A few kilometers",
        "Thousands of km",
        "Millions of km",
      ],
      correct: 3,
    },
    {
      id: 6,
      question: "How many known asteroids are in the belt?",
      options: ["About 1,000", "About 10,000", "About 100,000", "Over 1 million"],
      correct: 3,
    },
    {
      id: 7,
      question: "What are the three main types of asteroids?",
      options: [
        "Gas, Ice, Rock",
        "Carbon, Silicate, Metal",
        "Iron, Nickel, Copper",
        "Small, Medium, Large",
      ],
      correct: 1,
    },
    {
      id: 8,
      question: "How wide is the asteroid belt?",
      options: ["~1 million km", "~50 million km", "~150 million km", "~500 million km"],
      correct: 2,
    },
    {
      id: 9,
      question: "Are asteroids in the belt densely packed like in movies?",
      options: [
        "Yes, they constantly collide",
        "No, they are widely spaced apart",
        "Only in the inner belt",
        "Yes, you cannot fly through it",
      ],
      correct: 1,
    },
    {
      id: 10,
      question: "What is the diameter of Ceres?",
      options: ["100 km", "480 km", "940 km", "2,377 km"],
      correct: 2,
    },
  ],
};

export const getQuizQuestions = (planetId) => {
  return quizQuestions[planetId] || null;
};
